### PR TITLE
Cross platform compatability

### PR DESCRIPTION
**Pull request by rafaqz**
Hi Michael, I wrote an .onLoad hook to load the libraries manually, and removed useDynLib() calls as they were our problem, and were not flexible enough to allow multiple library paths.

 It will need testing on win/mac, but it's working on linux.

### CODE REVIEW

**Comment by rafaqz** [comment]
Hang on I broke something...

**Comment by rafaqz** [comment]
Ok that should be all working now

**Comment by rafaqz** [comment]
Just realised one of the vignettes is breaking from this change... will attemp to fix

**Comment by simon-tarr** [comment]
Hello rafaqz, thanks for taking the time to integrate Linux support into the package. I am currently trying to run NicheMapR on Microsoft's Azure cloud platform using the package doAzureParallel. This package builds upon the popular doParallel package to enable parallel jobs to be run in the cloud.

On request, the doAzureParallel package will first create a Linux-based DVSM (Data Science Virtual Machine (DSVM)) and then install packages, either from CRAN or GitHub. I have attempted to provision a pool installing NicheMapR (from master branch) but it fails. I have trawled the error logs and I have identified where it's failing. I thought I would post it here as it may be useful for debugging any future issues on Linux:

```
gfortran   -fpic  -g -O2  -c gads.f -o gads.o
gcc -std=gnu99 -shared -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -o NicheMapR.so gads.o -lgfortran -lm -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -lR
mv NicheMapR.so gads.so
Error : .onLoad failed in loadNamespace() for 'NicheMapR', details:
  call: dyn.load(micro_lib)
  error: unable to load shared object '/usr/lib64/microsoft-r/3.3/lib64/R/library/NicheMapR/libs/linux/MICROCLIMATE.so':
  libgfortran.so.4: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
```

**Comment by rafaqz** [comment]
Including binary libs is not very common so there are bound to be some issues with this, thanks for pointing it out.

It seems the main question is if MICROCLIMATE.so is actually in the folder /usr/lib64/microsoft-r/3.3/lib64/R/library/NicheMapR/libs/linux/ ?

If so the question is why is it not there? The standard R install() process normally copies everything in the inst/ folder to the project directory so NicheMapR/inst/libs/linux/* ends up in NicheMapR/libs/linux/*  - but this is missing in the error. For some reason your provisioning process is not doing a normal install. A build flag like --no-inst or --no-libs could be responsible, but some other flags could do this too. What is the build process for the NichMapR package in your provisioning?

**Comment by simon-tarr** [comment]
Thanks for the reply and extra information. With regards to the build process - I have no idea I'm afraid but it's something that I can find out with a bit of research. Your reply has given me something to work with so I'll look to track down this information during the week. Many thanks.

**Comment by brnleehng** [comment]
@rafaqz 

Hi, 

In doAzureParallel, we used the `devtools::install_github` to install our github packages. This does not seem to work. So I switched it to downloading the .tar.gz file and installing with command `install.packages`

Which file are we suppose to download? https://github.com/mrke/NicheMapR/releases -  I tried installing the .tar.gz file but I ran into the same issue... 

Commands on Command Line:
`
wget 'https://github.com/mrke/NicheMapR/archive/v1.1.3.tar.gz';
Rscript -e 'args <- commandArgs(TRUE)' -e 'install.packages(paste0(args[1], args[2], args[3]), repos = NULL, type = .Platform$pkgType)' $AZ_BATCH_NODE_STARTUP_DIR /wd/ v1.1.3.tar.gz;
`

Error Code: 
`
  gfortran   -fpic  -g -O2  -c gads.f -o gads.o
  gcc -std=gnu99 -shared -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -o NicheMapR.so gads.o -lgfortran -lm -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -lR
  mv NicheMapR.so gads.so
  Error : .onLoad failed in loadNamespace() for 'NicheMapR', details:
    call: dyn.load(micro_lib)
    error: unable to load shared object '/usr/lib64/microsoft-r/3.3/lib64/R/library/NicheMapR/libs/linux/MICROCLIMATE.so':
    libgfortran.so.4: cannot open shared object file: No such file or directory
  Error: loading failed
  Execution halted
`

However, when I downloaded .tgz (Mac file) I was able to install it but was unable to run any functions from the package (Which makes sense, the machines we are running are Centos-OS) I see the  MICROCLIMATE.so in the .tgz file.

**Comment by mrke** [comment]
Hi Brian,

At the moment the .tar.gz and .zip files on the releases page don’t include the Linux binaries, so you’ll need to use devtools::install_github for now.

All the best,
Mike

**Comment by brnleehng** [comment]
Hi,

I tried running devtools::install_github("mrke/NicheMapR") on Ubuntu. Am I doing something wrong here? 

screen shot 2017-08-23 at 6 58 51 pm

**Comment by rafaqz** [comment]
That is weird! the identical command works just fine on my Arch linux system. All I can think of is that my R version (3.4.1) might be ahead of yours, and I've done something that doesn't work on older versions?

**Comment by rafaqz** [comment]
I'll try it on my ubuntu server.

**Comment by rafaqz** [comment]
Ok I can confirm the same issue on Ubuntu Trusty, with the same version of R, so that's not the issue. I'll look into it.

**Comment by rafaqz** [comment]
I've actually misread your error - the problem is libgfortran.so.4 not existing. 

I compiled and run these binaries on arch linux, which has the bleeding edge fortran compiler gfortran7 which needs libgfortran.so.4. But you probably have libgfortran.so.3 on ubuntu. Maybe you can install the gfortran-7 package if you're using a recent version of ubuntu? It doesn't look easy on my old xenial server unfortunately...

**Comment by simon-tarr** [comment]
Is it possible to recompile using an older FORTRAN compiler which instead requires libgfortran.so.3?

**Comment by rafaqz** [comment]
Yes, but lets hope the newer version runs older binaries so I I can use it too! otherwise it would undermine my reason for doing this in the first place. It's becoming painfully obvious why using closed-source libraries is so rare in the R world...

**Comment by rafaqz** [comment]
I had to upgrade my server as it wouldn't compile the code (to old this time!!) The bad news is the binaries compiled for libgfortran.so.3 do not work with the newer fortran library libgfortran.so.4. So including this binary will mean I can't use NicheMapR locally. 

But I can maintain a branch for the newer fortran in my fork and put in a pull request to include your version in master here, as I'm guessing I'm the only user with libgfortran.so.4.

**Comment by rafaqz** [comment]
Done. Before I put in a pull request to mrke please test the changes from my fork:

devtools::install_github("rafaqz/NicheMapR")

**Comment by simon-tarr** [comment]
Thanks so much for taking the time to do this - i'ts very much appreciated. I will test the changes in the new fork and will get back to you soon. Simon.

**Comment by simon-tarr** [comment]
Rafael - I can confirm that your fork works when provisioning a pool via doAzureParallel (on Linux nodes)! Upon pool creation, all nodes become 'idle' which means all packages have been successfully installed and are awaiting instructions. I will have to do some further testing today to ensure that all functions within the package work but, at the moment, a big, big hurdle has been overcome. Thank you once again.

**Comment by rafaqz** [comment]
Great I'll put in the pull request.

**Comment by simon-tarr** [comment]
I have forked your changes above to my own repository - I have some changes to a few of the functions as I have created my own custom climate database. I have forked so that I can provision my pools with the amended code without it interfering with anyone else's work. (I'm new to Git and still becoming familiar with how it all works!).

**Pull request merged**
